CREATE TABLE IF NOT EXISTS posts
(idpost int NOT NULL AUTO_INCREMENT,
title VARCHAR(60) NOT NULL,
content LONGTEXT,
image VARCHAR(50),
posted DATETIME,
updateat DATETIME NOT NULL,
userid VARCHAR(256) NOT NULL,
ispublished BIT(1) NOT NULL DEFAULT 0,
PRIMARY KEY(idpost));

CREATE TABLE IF NOT EXISTS settings
(settingname VARCHAR(100) NOT NULL,
settingvalue VARCHAR(250) NOT NULL,
PRIMARY KEY(settingname));